In [3]:
import numpy as np


In [4]:
arr = np.arange(5)

In [5]:
arr

array([0, 1, 2, 3, 4])

In [6]:
np.save('myarr',arr)
# name and array you want to save


In [7]:
arr = np.arange(10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.load('myarr.npy')

array([0, 1, 2, 3, 4])

In [11]:
arr1 = np.load('myarr.npy')

In [12]:
arr2 = arr

In [13]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.savez('ziparray.npz', x = arr1, y = arr2)
#will be stored as a zip
# we can store multiple at once


In [15]:
archieve_array = np.load('ziparray.npz')
#we can load those into another variable and view them 

In [17]:
archieve_array

In [21]:
archieve_array['x']
# variable name with the array which we saved it with in this case x

array([0, 1, 2, 3, 4])

In [22]:
archieve_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr = np.array([[1,2,3], [4,5,6]])

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.savetxt('mytestarray.txt' ,arr,delimiter=',')
# we can save an array as a text file 
# we can do it by naming the text file
#giving the array you want to save 
# and delimiter 
# delimiter is what should be between th enumbers 


In [28]:
arr = np.loadtxt('mytestarray.txt', delimiter=',')

In [29]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])