In [5]:
import numpy as np

In [ ]:
mylist1 = [1,2,3,4]
# one way to create an array is by creating a list and the passing that 
# list to an array using NP

In [ ]:
my_array1 = np.array(mylist1)

In [ ]:
my_array1

In [ ]:
mylist2 =[4,5,6,7,8]


In [ ]:
mylists = mylist1+mylist2

In [ ]:
mylists


In [ ]:
# or we can do 
mylists = [mylist1, mylist2]

In [ ]:
mylists


In [ ]:
my_array2 = np.array(mylists)

In [ ]:
my_array2

In [6]:
mylist1 = [1,2,3,4]

In [ ]:
myarray1 = np.array(mylist1)

In [7]:
mylist2 = [11,22,33,44]

In [8]:
my_lists = [mylist1, mylist2]

In [9]:
myarray2 = np.array(my_lists)

In [10]:
myarray2
# multi dinmensional array is done by creating two lists ad conversting them to an array


array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
myarray2.shape
# shape give rows * colums 

(2, 4)

In [ ]:
myarray2.dtype

In [ ]:
np.zeros(5)

In [ ]:
myzerosarray = np.zeros(5)


In [ ]:
myzerosarray.dtype
#check datatype

In [ ]:
np.ones([5,5])
#array of xeros

In [12]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.eye(5)
# identity matrics creation

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [16]:
np.arange(0,500,50)

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])