In [1]:
import numpy as np

In [10]:
arr = np.arange(0,11)
#create array using Range

SyntaxError: invalid syntax (<ipython-input-10-a3b1e7923ea3>, line 2)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:6]
printing range

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[0:5] = 100
#setting the values at the index to some value

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:6]
# slice of an array

In [13]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr
# all the changes will be reflected in to the original array 
# this is the main use with the numpy 
# memoruy managemnet is very good


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy = arr.copy()

In [22]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_2d = np.array(([1,2,3,4,5],[5,10,15,20,25]))
# 2d array 

In [26]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 5, 10, 15, 20, 25]])

In [27]:
arr_2d[1]
# this will rint first row because first list is stored on the first index

array([ 5, 10, 15, 20, 25])

arr_2d[1][2]

In [28]:
arr_2d[1][2]
# printing first row 3rd column

15

In [33]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 5, 10, 15, 20, 25]])

In [30]:
slice_of_array = arr_2d[1:][3:5]

In [31]:
slice_of_array

array([], shape=(0, 5), dtype=int64)

In [35]:
arr_2d[:2,1:]

array([[ 2,  3,  4,  5],
       [10, 15, 20, 25]])

In [36]:
arr_2d[1]

array([ 5, 10, 15, 20, 25])

In [39]:
# fancy indexing is something like we can select what ever row we want
arr_2d = np.zeros((10,10))

In [40]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
arr_length = arr_2d.shape[1]

In [42]:
arr_length

10

In [43]:
for i in range(arr_length):
    arr_2d[i] = i

In [44]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [47]:
arr_2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [48]:
arr_2d[[6,4,2,7]]
# fancy indexing is something like we can select what ever row we want

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])