In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ser1 = Series([0,1,2],index=['T','U','V'])

In [9]:
ser2 = Series([3,4], index = ['X','Y'])

In [10]:
ser1


T    0
U    1
V    2
dtype: int64

In [11]:
ser2

X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [15]:
pd.concat([ser1])

T    0
U    1
V    2
dtype: int64

In [18]:
pd.concat([ser1,ser2],axis =1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [19]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [20]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','y','Z'])

In [21]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [22]:
dframe1

X         y         Z
0 -0.631530 -0.453754 -0.559707
1 -0.580116  0.366315  0.050844
2 -2.295765 -0.034030  0.208099
3 -1.094546  0.376661  1.430597

In [23]:
dframe2

Y         Q         X
0  1.573363  0.909589  0.497279
1 -2.323890  0.399826  0.126976
2 -1.516377 -0.929363  0.807712

In [24]:
pd.concat([dframe1, dframe2])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z         y
0       NaN -0.631530       NaN -0.559707 -0.453754
1       NaN -0.580116       NaN  0.050844  0.366315
2       NaN -2.295765       NaN  0.208099 -0.034030
3       NaN -1.094546       NaN  1.430597  0.376661
0  0.909589  0.497279  1.573363       NaN       NaN
1  0.399826  0.126976 -2.323890       NaN       NaN
2 -0.929363  0.807712 -1.516377       NaN       NaN

In [25]:
pd.concat([dframe1,dframe2],ignore_index =True)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z         y
0       NaN -0.631530       NaN -0.559707 -0.453754
1       NaN -0.580116       NaN  0.050844  0.366315
2       NaN -2.295765       NaN  0.208099 -0.034030
3       NaN -1.094546       NaN  1.430597  0.376661
4  0.909589  0.497279  1.573363       NaN       NaN
5  0.399826  0.126976 -2.323890       NaN       NaN
6 -0.929363  0.807712 -1.516377       NaN       NaN