In [36]:

import numpy as np


In [37]:
5/2

2.5

In [38]:
mylist1 = [1,2,3,4,5]
mylist2 = [8,9,10,11]
mylists = [mylist1,mylist2]

In [39]:
arr1 = np.array([mylists])

In [40]:
arr1

array([[list([1, 2, 3, 4, 5]), list([8, 9, 10, 11])]], dtype=object)

In [41]:
myarray = np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [42]:
myarray

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [43]:
myarray*myarray
# multiplication one on one

array([[ 1,  4,  9, 16, 25],
       [36, 49, 64, 81,  0]])

In [44]:
myarray- myarray

#subtraction one on one

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [46]:
myarray

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [47]:
myarray**3
# every elemnet in array power 3

array([[  1,   8,  27,  64, 125],
       [216, 343, 512, 729,   0]])