In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
a = np.random.randn(10)

In [7]:
a

array([ 0.1192508 ,  0.83183153,  0.55327473,  0.92805771, -0.79255944,
       -0.54765694,  0.48636827, -1.65557484, -0.52066788,  1.64645523])

In [11]:
b = np.random.randn(10)

In [12]:
b

array([ 0.13787911, -0.97592983,  0.84951646,  1.12021909,  0.55757556,
       -1.86335817, -1.49977804,  0.24744695, -0.74097755, -0.66886092])

In [13]:
# binary Fnctiona 

np.add(a,b)

array([ 0.25712991, -0.14409829,  1.40279119,  2.0482768 , -0.23498389,
       -2.41101511, -1.01340976, -1.40812789, -1.26164544,  0.97759431])

In [14]:
np.max(a)

1.6464552284659584

In [15]:
np.maximum(a,b)

array([ 0.13787911,  0.83183153,  0.84951646,  1.12021909,  0.55757556,
       -0.54765694,  0.48636827,  0.24744695, -0.52066788,  1.64645523])

In [17]:
np.max(a,b)

TypeError: only integer scalar arrays can be converted to a scalar index

In [18]:
np.minimum(a,b)

array([ 0.1192508 , -0.97592983,  0.55327473,  0.92805771, -0.79255944,
       -1.86335817, -1.49977804, -1.65557484, -0.74097755, -0.66886092])

In [19]:
import webbrowser

In [ ]:
webbrowser.open(#link#)
    